server:
  port: 8082


clickhouse:
  driverClassName: ru.yandex.clickhouse.ClickHouseDriver
  url: jdbc:clickhouse://192.168.3.137:8123
  password: cOhglnbf
  initialSize: 10
  maxActive: 100
  minIdle: 10
  maxWait: 6000
spring:
  datasource:
    url: jdbc:clickhouse://192.168.3.137:8123/study
    password: cOhglnbf
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # ??????s
    db-config:
      # ???
      logic-not-delete-value: 1
      # ???
      logic-delete-value: 0